name: Build and package theme

on:
  push:
    branches:
      - main
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
          registry-url: https://registry.npmjs.org/

      - name: Install dependencies
        run: npm install pnpm -g

      - name: Build TypeScript files
        run: pnpm run build

      - name: Create ZIP package
        run: zip -r shokaX.zip * -x '*.ts' "node_modules/*" ".github/*" "docs/*"

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: shokaX-stable
          path: shokaX.zip

  test:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
          registry-url: https://registry.npmjs.org/

      - name: Get theme
        uses: actions/checkout@v3

      - name: Init environment
        run: |
          npm install pnpm -g
          pnpm install

      - name: Test
        run: |
          tsc
          pnpm test